<?php
?>
<div class="topmainheader">
    <div class="left-top-header">
        <span class="fasthead"> Your Uk Procurement Source for American Industrial parts  </span>
        <a href="#" id="chattingbox" class="box"><span class="chatit"><i class="fa fa-comments"></i>Chat Now</span>
        <span class="online"> online </span>
        </a>
    </div>
    <div class="right-top-header">
        <ul>
            <li class="right-header">
                <a href="@"><i class="fa fa-phone"></i><span class="numbershow"></span>+44 203 287 5224</a>
            </li>
            <li class="right-header"><a href="#"><i class=" fa fa-envelope"></i><span>sales@raptorsupplies.com</span></a></li>
            <li class="right-header"><a href="#"><i class="fa fa-whatsapp" ></i><span>Whatsapp</span></a></li>
        </ul>
    </div>
</div>
<section class="navsection">
    <header class="navbar">
            <div class="div-navbar">
                <navbar class="navbar">
                    <ul class="navbar-icon">
                        <li class="nav">Catalogue</li>
                        <li class="nav">About</li>
                        <li class="nav">Contact Us</li>
                        <li class="nav">Submit RFQ</li>
                        <li class="nav" id="vendorregistration" >VENDOR REGISTRATION</li>
                    </ul>
                    <!-- <div class="header-image">
                        <img src="images/raptorlogo.png" >
                    </div> -->
                </navbar>
            </div>
        
    </header>
</section>