<?php
?>
<div class="topmainheader">
    <div class="left-top-header">
        <span class="fasthead"> Your Uk Procurement Source for American Industrial parts  </span>
        <a href="#" id="chattingbox" class="box"><span class="chatit"><i class="fa fa-comments"></i>Chat Now</span>
        <span class="online"> online </span>
        </a>
    </div>
    <div class="right-top-header">
        <ul class="top-header-ul">
            <li class="right-header">
                <a href="@"><i class="fa fa-phone"></i><span class="numbershow"></span>+44 203 287 5224</a>
            </li>
            <li class="right-header"><a href="#"><i class=" fa fa-envelope"></i><span>sales@raptorsupplies.com</span></a></li>
            <li class="right-header"><a href="#"><i class="fa newsprite whatsappicon" style="margin: 0px 8px;"></i><span style="position: absolute; bottom: 10px;">Whatsapp</span></a></li>
        </ul>
    </div>
</div>
<section class="navsection">
    <header class="navbar">
            <div class="div-navbar">
                <navbar class="navbar">
                    <ul class="navbar-icon">
                        <li class="nav toggle">Catalogue<i class="fa fa-arrow-down" id="toggle" style="color: white"></i>
                            <ul class="inside-catalogue togg">
                                    <li class="togglebox">
                                        <div class="togglediv">
                                        <h3 class="h3-tag" >Categories</h2>
                                        <p class="para">Can't find something ? We can source any MRO  Product</p>
                                        <hr>
                                        </div>
                                        
                                    </li>

                                    <li class="togglebox togglebox-2">
                                        <div class="toggle-box2-div">
                                            <h3 class="h3-tag">Brands</h2>
                                            <p class="para">
                                            We supply top American  brands to your doorstep within days 
                                            </p>
                                            <hr>
                                        </div>
                                    </li>
                                    <li class="togglebox toggle-box-3">
                                        <div class="toggle-box3-div">
                                            <h3 class="h3-tag">We can spource any MRO product for you. Talk to one of our procurement specialists</h3>
                                            <p class="para">We can supply Us products not listed here and, unlike most  companies , we enjoy a real companies</p>
                                        </div>
                                    </li>
                            </ul>
                        </li>
                        <li class="nav nav-hover">About</li>
                        <li class="nav nav-hover">Contact Us</li>
                        <li class="nav nav-hover">Submit RFQ</li>
                        <li class="nav " id="vendorregistration" >VENDOR REGISTRATION</li>
                    </ul>

                    <!-- images for logo -->
                    <div class="image">
                        <img src="images/raptorlogo.png" >
                    </div>
                    <div class="sign-in">
                        <button class="sign-btn">Sign In</button>
                    </div>
                   
                </navbar>
            </div>
        
    </header>
</section>
<!-- 
app/design/frontend/Raptor/raptortheme/
Magento_Theme/templates/html/header/web/images/raptorlogo.png -->

<scr